### ISSUE TITLE
No way to stop the IPFS daemon once started

### ISSUE THREAD

**Issue by axelsimon** [ligi/IPFSDroid#12]
Hi,
If you install IPFSDroid and then install the daemon, it starts normally but there is no (obvious?) way of shutting it down, except rebooting the phone.

One would expect the long-term notification to take you to a menu where you can stop the daemon, or even maybe to have that option in the notification, on recent versions of Android.
Thanks!

**Comment by ligi** [comment]
depends on https://github.com/ipfs/go-ipfs/issues/3034

**Comment by jcgruenhage** [comment]
I think the original issue is fixed. If someone reminds me to do it, I might be able to add a shutdown button

**Comment by jcgruenhage** [comment]
From what I see in the commits, the daemon is currently killed when you want to stop it. go-ipfs added a shutdown command, you might want to use that instead.
