### ISSUE TITLE
how can i ask specific peer to download a specific file which is added by me on android platform?

### ISSUE THREAD

**Issue by sagar117** [ligi/IPFSDroid#15]
i wanna others peers to download data which is added by me i didn't find any way to do this on android so guide me

**Comment by ligi** [comment]
so you want to add on android and get on PC? After adding you get a hash and you use this to get the file

**Comment by sagar117** [comment]
i want  to get that file on android

**Comment by ligi** [comment]
then you must click on an url with the hash

**Comment by sagar117** [comment]
ok thanks, can you please answer if i add large file then ipfs will chunk it in to smaller one is there any way so that i can serve that files to particular peer with the help of other peer simultaneously

**Comment by ligi** [comment]
I do not understand the question - and it seems to be ipfs and not
android specific - so I think better ask in go-ipfs

**Comment by sagar117** [comment]
ok thank
