### ISSUE TITLE
what should  i have to do for use all ipfs commands on android?

### ISSUE THREAD

**Issue by sagar117** [ligi/IPFSDroid#16]
I couldn't find all ipfs commands available on android platform but i have to use that commands so how can i do that .

**Comment by ligi** [comment]
can you elaborate?

**Comment by sagar117** [comment]
Ipfs add command is given in ipfs for adding files or text but suppose I
want to use other commands like ipfs swarm peers or ipfs dht query so how
can I achieve that how you are able to run ipfs add and other commands on
Android platform?

**Comment by ligi** [comment]
did you have a look into: https://github.com/ligi/ipfs-api-kotlin ?
It is not yet possible through IPFSDroid without modifications - I wait
for the IPFS core go team to implement throttling a stop command before
continuing with IPFSDroid - without throttling mobile is really bad UX
currently. After this is there I will add an api to IPFSDroid ( through
contentprovider or AIDL )

**Comment by sagar117** [comment]
ok got it thanks
