### ISSUE TITLE
Large file add issue in IPFS?

### ISSUE THREAD

**Issue by sagar117** [ligi/IPFSDroid#18]
when i am trying to add large files over 40-50 MB in to IPFS mobile is getting hang i tried by changing tmp file location to external storage still it's happening.

**Comment by jcgruenhage** [comment]
I've just successfully added a 1GB file :D

**Comment by ligi** [comment]
@jcgruenhage cool - thanks for the test!

**Comment by ligi** [comment]
@jcgruenhage was that with IPFS 0.4.10?

**Comment by jcgruenhage** [comment]
That was with whatever ipfsdroid downloaded yesterday ^^

**Comment by jcgruenhage** [comment]
Just checked, it was ipfs 0.4.2. Is the F-Droid build maybe a bit out of date?

**Comment by ligi** [comment]
Yea - wasn't updating this app for a while - the new version should be on FDroid soonish
