### ISSUE TITLE
Resolve 30-Day Notification of Google Play Developer Term Violation

### ISSUE THREAD

**Issue by ligi** [ligi/IPFSDroid#24]
> Hi Developers at ligi,
> 
> We're writing to let you know that your app, IPFSDroid, with package name org.ligi.ipfsdroid, violates the Malicious Behavior policy.
> 
> Policy issue: An app downloaded from Google Play may not modify, replace, or update its own APK binary code using any method other than Google Play's update mechanism. Additionally, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.
> 
> Action required: Please bring your app into compliance within 30 days of the issuance of this notification, or your app will be removed from Google Play.
> 
> If you have additional apps in your catalog, make sure they comply with our Malicious Behavior policy. You may want to review the Developer Program Policies or watch this short video for more policy guidance and best practices.
> 
> The Google Play Team

**Comment by ligi** [comment]
here the policy: https://play.google.com/about/privacy-security/malicious-behavior/

**Comment by hobofan** [comment]
This should be easily resolvable by copying over the IPFS binary at build instead of downloading it at runtime, no?

**Comment by ligi** [comment]
Technically this is easy - but it comes with some drawbacks. Mainly that the binaries are big and I would need several of them (x86*,arm*) in the apk. Don't really want to go the split-apk route as this leads to some hassle when rolling out versions. Also I want to include the new version 0.4.11 and @Whyrusleeping mentioned it should be released soon. (https://www.reddit.com/r/ipfs/comments/70wja8/goipfs_0411_release_candidate/dn86q76/) Otherwise there would be 2 releases in short order.
Also I would need to think how to do it on FDroid. Multiple things to think about. Was also liking the fact that the binary could be optional (fallback with the gateway) - but I will have to do it soon as otherwise the app might be taken from the store ..

**Comment by hobofan** [comment]
As far as 0.4.11 goes, it seems that the release version was finalized yesterday: https://github.com/ipfs/go-ipfs/pull/4266

> Additionally, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.

I'm wondering if it would be possible to circumvent this limitation by letting the user choose an executable from the filesystem instead of downloading it in the app.

**Comment by ligi** [comment]
Ah nice - thanks for the info! Interesting idea with the Filesystem - not sure if it will be OK for google - IANAL ..-)

**Comment by ligi** [comment]
Just compiled the binaries - unfortunately they even got bigger: 
```
⋊> /t/w/s/g/i/go-ipfs on master ⨯ ls -l *16* -lh
-rwxr-xr-x 1 root root  40M Okt  1 09:33 ipfs-android-16-386*
-rwxr-xr-x 1 root root  40M Okt  1 09:32 ipfs-android-16-arm*
```
they where 26M before - means now 80MB for the apk - quite big ..

**Comment by whyrusleeping** [comment]
Ooof, im sorry. They got a little bit bigger for 0.4.11. but not nearly
double. I wonder what happened

**Comment by ligi** [comment]
@cketti had a nice hint - by adding -ldflags "-s -w" I could reduce the filesize drastically again (now we are ~ where we where before 0.4.11)

```
⋊> /t/w/s/g/i/go-ipfs on master ⨯ ls -lh *android* -lh
-rwxr-xr-x 1 root root  24M Okt  2 14:21 ipfs-android-16-386*
-rwxr-xr-x 1 root root  23M Okt  2 14:20 ipfs-android-16-arm*
```

@karalabe what do you think about adding these ldflags also to the go-ethereum Makefile for the Android target? Would be great to also reduce the filesize there ..-)

**Comment by ligi** [comment]
v0.11 which closes this issue is now in beta
