### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by iraamaro** [ligi/IPFSDroid#35]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by ligi** [comment]
Hi - thanks for the question. Usually I use transifex for translations. But there should be really something decentralized ;-)
That said: I am not yet sure if it is worth translating it in the current form. It is an experiment with IPFS on mobile - unfortunately this experiment showed me IPFS is not (yet) really fit for mobile use. That being said I was recently watching a talk by @jbenet that hinted mobile will soon be focus of the project so things might change.

**Comment by hanelore** [comment]
Thanks, so I will wait and be alert with the discussion.
