### ISSUE TITLE
Add ability to use go-ipfs implementation

### ISSUE THREAD

**Issue by ligi** [ligi/IPFSDroid#4]
currently blocked by: https://github.com/karalabe/xgo/issues/48

**Comment by ligi** [comment]
not blocked anymore - thanks to @karalabe input:

#adb shell
root@generic_x86_64:/ # cd /data/local/tmp/                                    
root@generic_x86_64:/ # ./ipfs-android-16-386 cat QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme                         <
Hello and Welcome to IPFS!

██╗██████╗ ███████╗███████╗
██║██╔══██╗██╔════╝██╔════╝
██║██████╔╝█████╗  ███████╗
██║██╔═══╝ ██╔══╝  ╚════██║
██║██║     ██║     ███████║
╚═╝╚═╝     ╚═╝     ╚══════╝

If you're seeing this, you have successfully installed
IPFS and are now interfacing with the ipfs merkledag!

 -------------------------------------------------------
| Warning:                                              |
|   This is alpha software. Use at your own discretion! |
|   Much is missing or lacking polish. There are bugs.  |
|   Not yet secure. Read the security notes for more.   |
 -------------------------------------------------------

Check out some of the other files in this directory:

  ./about
  ./help
  ./quick-start     <-- usage examples
  ./readme          <-- this file
  ./security-notes

**Comment by ligi** [comment]
IPFS 0.4 now includes the ipfs binaries for ARM and X86 - there is one problem with ARM though - ARM hangs on "ipfs init" - it works fine on x86 ( emulator and device ) - not yet sure how to debug/fix this - perhaps @lgierth has some idea

**Comment by lgierth** [comment]
Is https://github.com/ipfs/go-ipfs/issues/2748 possibly related? It's a regression introduced in 0.4.2 and fixed on master

**Comment by ligi** [comment]
when it is introduced in 0.4.2 this cannot be the reason - I am running 0.4.1 in this
